/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.api;

import br.com.fidias.consultar_placa.ApiCallback;
import br.com.fidias.consultar_placa.ApiClient;
import br.com.fidias.consultar_placa.ApiException;
import br.com.fidias.consultar_placa.ApiResponse;
import br.com.fidias.consultar_placa.Configuration;
import br.com.fidias.consultar_placa.Pair;
import br.com.fidias.consultar_placa.ProgressRequestBody;
import br.com.fidias.consultar_placa.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import br.com.fidias.consultar_placa.model.Error;
import br.com.fidias.consultar_placa.model.Veiculo;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultApi {
    private ApiClient localVarApiClient;

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for consultarPlacaGet
     * @param placa  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Consultar Placa - Informações básicas </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Erro de Requisição </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Permissão Negada </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Limite de Requisições Excedido </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro Interno </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call consultarPlacaGetCall(String placa, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/consultarPlaca";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (placa != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("placa", placa));
        }

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call consultarPlacaGetValidateBeforeCall(String placa, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = consultarPlacaGetCall(placa, _callback);
        return localVarCall;

    }

    /**
     * 
     * 
     * @param placa  (optional)
     * @return Veiculo
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Consultar Placa - Informações básicas </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Erro de Requisição </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Permissão Negada </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Limite de Requisições Excedido </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro Interno </td><td>  -  </td></tr>
     </table>
     */
    public Veiculo consultarPlacaGet(String placa) throws ApiException {
        ApiResponse<Veiculo> localVarResp = consultarPlacaGetWithHttpInfo(placa);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param placa  (optional)
     * @return ApiResponse&lt;Veiculo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Consultar Placa - Informações básicas </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Erro de Requisição </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Permissão Negada </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Limite de Requisições Excedido </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro Interno </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Veiculo> consultarPlacaGetWithHttpInfo(String placa) throws ApiException {
        okhttp3.Call localVarCall = consultarPlacaGetValidateBeforeCall(placa, null);
        Type localVarReturnType = new TypeToken<Veiculo>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param placa  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Consultar Placa - Informações básicas </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Erro de Requisição </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Permissão Negada </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Limite de Requisições Excedido </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro Interno </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call consultarPlacaGetAsync(String placa, final ApiCallback<Veiculo> _callback) throws ApiException {

        okhttp3.Call localVarCall = consultarPlacaGetValidateBeforeCall(placa, _callback);
        Type localVarReturnType = new TypeToken<Veiculo>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
