/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DadosVeiculo
 */
public class DadosVeiculoTest {
    private final DadosVeiculo model = new DadosVeiculo();

    /**
     * Model tests for DadosVeiculo
     */
    @Test
    public void testDadosVeiculo() {
        // TODO: test DadosVeiculo
    }

    /**
     * Test the property 'placa'
     */
    @Test
    public void placaTest() {
        // TODO: test placa
    }

    /**
     * Test the property 'chassi'
     */
    @Test
    public void chassiTest() {
        // TODO: test chassi
    }

    /**
     * Test the property 'anoFabricacao'
     */
    @Test
    public void anoFabricacaoTest() {
        // TODO: test anoFabricacao
    }

    /**
     * Test the property 'anoModelo'
     */
    @Test
    public void anoModeloTest() {
        // TODO: test anoModelo
    }

    /**
     * Test the property 'marca'
     */
    @Test
    public void marcaTest() {
        // TODO: test marca
    }

    /**
     * Test the property 'modelo'
     */
    @Test
    public void modeloTest() {
        // TODO: test modelo
    }

    /**
     * Test the property 'cor'
     */
    @Test
    public void corTest() {
        // TODO: test cor
    }

    /**
     * Test the property 'segmento'
     */
    @Test
    public void segmentoTest() {
        // TODO: test segmento
    }

    /**
     * Test the property 'combustivel'
     */
    @Test
    public void combustivelTest() {
        // TODO: test combustivel
    }

    /**
     * Test the property 'procedencia'
     */
    @Test
    public void procedenciaTest() {
        // TODO: test procedencia
    }

    /**
     * Test the property 'municipio'
     */
    @Test
    public void municipioTest() {
        // TODO: test municipio
    }

    /**
     * Test the property 'ufMunicipio'
     */
    @Test
    public void ufMunicipioTest() {
        // TODO: test ufMunicipio
    }

}
