/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DadosCarga
 */
public class DadosCargaTest {
    private final DadosCarga model = new DadosCarga();

    /**
     * Model tests for DadosCarga
     */
    @Test
    public void testDadosCarga() {
        // TODO: test DadosCarga
    }

    /**
     * Test the property 'numeroEixos'
     */
    @Test
    public void numeroEixosTest() {
        // TODO: test numeroEixos
    }

    /**
     * Test the property 'capacidadeMaximaTracao'
     */
    @Test
    public void capacidadeMaximaTracaoTest() {
        // TODO: test capacidadeMaximaTracao
    }

    /**
     * Test the property 'capacidadePassageiro'
     */
    @Test
    public void capacidadePassageiroTest() {
        // TODO: test capacidadePassageiro
    }

}
