/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.model;

import br.com.fidias.consultar_placa.model.VeiculoDadosInformacoesVeiculo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VeiculoDados
 */
public class VeiculoDadosTest {
    private final VeiculoDados model = new VeiculoDados();

    /**
     * Model tests for VeiculoDados
     */
    @Test
    public void testVeiculoDados() {
        // TODO: test VeiculoDados
    }

    /**
     * Test the property 'informacoesVeiculo'
     */
    @Test
    public void informacoesVeiculoTest() {
        // TODO: test informacoesVeiculo
    }

}
