/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.model;

import br.com.fidias.consultar_placa.model.DadosCarga;
import br.com.fidias.consultar_placa.model.DadosTecnicos;
import br.com.fidias.consultar_placa.model.DadosVeiculo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VeiculoDadosInformacoesVeiculo
 */
public class VeiculoDadosInformacoesVeiculoTest {
    private final VeiculoDadosInformacoesVeiculo model = new VeiculoDadosInformacoesVeiculo();

    /**
     * Model tests for VeiculoDadosInformacoesVeiculo
     */
    @Test
    public void testVeiculoDadosInformacoesVeiculo() {
        // TODO: test VeiculoDadosInformacoesVeiculo
    }

    /**
     * Test the property 'dadosVeiculo'
     */
    @Test
    public void dadosVeiculoTest() {
        // TODO: test dadosVeiculo
    }

    /**
     * Test the property 'dadosTecnicos'
     */
    @Test
    public void dadosTecnicosTest() {
        // TODO: test dadosTecnicos
    }

    /**
     * Test the property 'dadosCarga'
     */
    @Test
    public void dadosCargaTest() {
        // TODO: test dadosCarga
    }

}
