/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DadosCarga
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-30T10:21:51.050-03:00[America/Fortaleza]")
public class DadosCarga {
  public static final String SERIALIZED_NAME_NUMERO_EIXOS = "numero_eixos";
  @SerializedName(SERIALIZED_NAME_NUMERO_EIXOS)
  private String numeroEixos;

  public static final String SERIALIZED_NAME_CAPACIDADE_MAXIMA_TRACAO = "capacidade_maxima_tracao";
  @SerializedName(SERIALIZED_NAME_CAPACIDADE_MAXIMA_TRACAO)
  private String capacidadeMaximaTracao;

  public static final String SERIALIZED_NAME_CAPACIDADE_PASSAGEIRO = "capacidade_passageiro";
  @SerializedName(SERIALIZED_NAME_CAPACIDADE_PASSAGEIRO)
  private String capacidadePassageiro;


  public DadosCarga numeroEixos(String numeroEixos) {
    
    this.numeroEixos = numeroEixos;
    return this;
  }

   /**
   * Get numeroEixos
   * @return numeroEixos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNumeroEixos() {
    return numeroEixos;
  }


  public void setNumeroEixos(String numeroEixos) {
    this.numeroEixos = numeroEixos;
  }


  public DadosCarga capacidadeMaximaTracao(String capacidadeMaximaTracao) {
    
    this.capacidadeMaximaTracao = capacidadeMaximaTracao;
    return this;
  }

   /**
   * Get capacidadeMaximaTracao
   * @return capacidadeMaximaTracao
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCapacidadeMaximaTracao() {
    return capacidadeMaximaTracao;
  }


  public void setCapacidadeMaximaTracao(String capacidadeMaximaTracao) {
    this.capacidadeMaximaTracao = capacidadeMaximaTracao;
  }


  public DadosCarga capacidadePassageiro(String capacidadePassageiro) {
    
    this.capacidadePassageiro = capacidadePassageiro;
    return this;
  }

   /**
   * Get capacidadePassageiro
   * @return capacidadePassageiro
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCapacidadePassageiro() {
    return capacidadePassageiro;
  }


  public void setCapacidadePassageiro(String capacidadePassageiro) {
    this.capacidadePassageiro = capacidadePassageiro;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DadosCarga dadosCarga = (DadosCarga) o;
    return Objects.equals(this.numeroEixos, dadosCarga.numeroEixos) &&
        Objects.equals(this.capacidadeMaximaTracao, dadosCarga.capacidadeMaximaTracao) &&
        Objects.equals(this.capacidadePassageiro, dadosCarga.capacidadePassageiro);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroEixos, capacidadeMaximaTracao, capacidadePassageiro);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DadosCarga {\n");
    sb.append("    numeroEixos: ").append(toIndentedString(numeroEixos)).append("\n");
    sb.append("    capacidadeMaximaTracao: ").append(toIndentedString(capacidadeMaximaTracao)).append("\n");
    sb.append("    capacidadePassageiro: ").append(toIndentedString(capacidadePassageiro)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

