/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DadosVeiculo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-30T10:21:51.050-03:00[America/Fortaleza]")
public class DadosVeiculo {
  public static final String SERIALIZED_NAME_PLACA = "placa";
  @SerializedName(SERIALIZED_NAME_PLACA)
  private String placa;

  public static final String SERIALIZED_NAME_CHASSI = "chassi";
  @SerializedName(SERIALIZED_NAME_CHASSI)
  private String chassi;

  public static final String SERIALIZED_NAME_ANO_FABRICACAO = "ano_fabricacao";
  @SerializedName(SERIALIZED_NAME_ANO_FABRICACAO)
  private String anoFabricacao;

  public static final String SERIALIZED_NAME_ANO_MODELO = "ano_modelo";
  @SerializedName(SERIALIZED_NAME_ANO_MODELO)
  private String anoModelo;

  public static final String SERIALIZED_NAME_MARCA = "marca";
  @SerializedName(SERIALIZED_NAME_MARCA)
  private String marca;

  public static final String SERIALIZED_NAME_MODELO = "modelo";
  @SerializedName(SERIALIZED_NAME_MODELO)
  private String modelo;

  public static final String SERIALIZED_NAME_COR = "cor";
  @SerializedName(SERIALIZED_NAME_COR)
  private String cor;

  public static final String SERIALIZED_NAME_SEGMENTO = "segmento";
  @SerializedName(SERIALIZED_NAME_SEGMENTO)
  private String segmento;

  public static final String SERIALIZED_NAME_COMBUSTIVEL = "combustivel";
  @SerializedName(SERIALIZED_NAME_COMBUSTIVEL)
  private String combustivel;

  public static final String SERIALIZED_NAME_PROCEDENCIA = "procedencia";
  @SerializedName(SERIALIZED_NAME_PROCEDENCIA)
  private String procedencia;

  public static final String SERIALIZED_NAME_MUNICIPIO = "municipio";
  @SerializedName(SERIALIZED_NAME_MUNICIPIO)
  private String municipio;

  public static final String SERIALIZED_NAME_UF_MUNICIPIO = "uf_municipio";
  @SerializedName(SERIALIZED_NAME_UF_MUNICIPIO)
  private String ufMunicipio;


  public DadosVeiculo placa(String placa) {
    
    this.placa = placa;
    return this;
  }

   /**
   * Get placa
   * @return placa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPlaca() {
    return placa;
  }


  public void setPlaca(String placa) {
    this.placa = placa;
  }


  public DadosVeiculo chassi(String chassi) {
    
    this.chassi = chassi;
    return this;
  }

   /**
   * Get chassi
   * @return chassi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getChassi() {
    return chassi;
  }


  public void setChassi(String chassi) {
    this.chassi = chassi;
  }


  public DadosVeiculo anoFabricacao(String anoFabricacao) {
    
    this.anoFabricacao = anoFabricacao;
    return this;
  }

   /**
   * Get anoFabricacao
   * @return anoFabricacao
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAnoFabricacao() {
    return anoFabricacao;
  }


  public void setAnoFabricacao(String anoFabricacao) {
    this.anoFabricacao = anoFabricacao;
  }


  public DadosVeiculo anoModelo(String anoModelo) {
    
    this.anoModelo = anoModelo;
    return this;
  }

   /**
   * Get anoModelo
   * @return anoModelo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAnoModelo() {
    return anoModelo;
  }


  public void setAnoModelo(String anoModelo) {
    this.anoModelo = anoModelo;
  }


  public DadosVeiculo marca(String marca) {
    
    this.marca = marca;
    return this;
  }

   /**
   * Get marca
   * @return marca
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMarca() {
    return marca;
  }


  public void setMarca(String marca) {
    this.marca = marca;
  }


  public DadosVeiculo modelo(String modelo) {
    
    this.modelo = modelo;
    return this;
  }

   /**
   * Get modelo
   * @return modelo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getModelo() {
    return modelo;
  }


  public void setModelo(String modelo) {
    this.modelo = modelo;
  }


  public DadosVeiculo cor(String cor) {
    
    this.cor = cor;
    return this;
  }

   /**
   * Get cor
   * @return cor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCor() {
    return cor;
  }


  public void setCor(String cor) {
    this.cor = cor;
  }


  public DadosVeiculo segmento(String segmento) {
    
    this.segmento = segmento;
    return this;
  }

   /**
   * Get segmento
   * @return segmento
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSegmento() {
    return segmento;
  }


  public void setSegmento(String segmento) {
    this.segmento = segmento;
  }


  public DadosVeiculo combustivel(String combustivel) {
    
    this.combustivel = combustivel;
    return this;
  }

   /**
   * Get combustivel
   * @return combustivel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCombustivel() {
    return combustivel;
  }


  public void setCombustivel(String combustivel) {
    this.combustivel = combustivel;
  }


  public DadosVeiculo procedencia(String procedencia) {
    
    this.procedencia = procedencia;
    return this;
  }

   /**
   * Get procedencia
   * @return procedencia
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProcedencia() {
    return procedencia;
  }


  public void setProcedencia(String procedencia) {
    this.procedencia = procedencia;
  }


  public DadosVeiculo municipio(String municipio) {
    
    this.municipio = municipio;
    return this;
  }

   /**
   * Get municipio
   * @return municipio
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMunicipio() {
    return municipio;
  }


  public void setMunicipio(String municipio) {
    this.municipio = municipio;
  }


  public DadosVeiculo ufMunicipio(String ufMunicipio) {
    
    this.ufMunicipio = ufMunicipio;
    return this;
  }

   /**
   * Get ufMunicipio
   * @return ufMunicipio
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUfMunicipio() {
    return ufMunicipio;
  }


  public void setUfMunicipio(String ufMunicipio) {
    this.ufMunicipio = ufMunicipio;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DadosVeiculo dadosVeiculo = (DadosVeiculo) o;
    return Objects.equals(this.placa, dadosVeiculo.placa) &&
        Objects.equals(this.chassi, dadosVeiculo.chassi) &&
        Objects.equals(this.anoFabricacao, dadosVeiculo.anoFabricacao) &&
        Objects.equals(this.anoModelo, dadosVeiculo.anoModelo) &&
        Objects.equals(this.marca, dadosVeiculo.marca) &&
        Objects.equals(this.modelo, dadosVeiculo.modelo) &&
        Objects.equals(this.cor, dadosVeiculo.cor) &&
        Objects.equals(this.segmento, dadosVeiculo.segmento) &&
        Objects.equals(this.combustivel, dadosVeiculo.combustivel) &&
        Objects.equals(this.procedencia, dadosVeiculo.procedencia) &&
        Objects.equals(this.municipio, dadosVeiculo.municipio) &&
        Objects.equals(this.ufMunicipio, dadosVeiculo.ufMunicipio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(placa, chassi, anoFabricacao, anoModelo, marca, modelo, cor, segmento, combustivel, procedencia, municipio, ufMunicipio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DadosVeiculo {\n");
    sb.append("    placa: ").append(toIndentedString(placa)).append("\n");
    sb.append("    chassi: ").append(toIndentedString(chassi)).append("\n");
    sb.append("    anoFabricacao: ").append(toIndentedString(anoFabricacao)).append("\n");
    sb.append("    anoModelo: ").append(toIndentedString(anoModelo)).append("\n");
    sb.append("    marca: ").append(toIndentedString(marca)).append("\n");
    sb.append("    modelo: ").append(toIndentedString(modelo)).append("\n");
    sb.append("    cor: ").append(toIndentedString(cor)).append("\n");
    sb.append("    segmento: ").append(toIndentedString(segmento)).append("\n");
    sb.append("    combustivel: ").append(toIndentedString(combustivel)).append("\n");
    sb.append("    procedencia: ").append(toIndentedString(procedencia)).append("\n");
    sb.append("    municipio: ").append(toIndentedString(municipio)).append("\n");
    sb.append("    ufMunicipio: ").append(toIndentedString(ufMunicipio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

