/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DadosTecnicos
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-30T10:21:51.050-03:00[America/Fortaleza]")
public class DadosTecnicos {
  public static final String SERIALIZED_NAME_TIPO_VEICULO = "tipo_veiculo";
  @SerializedName(SERIALIZED_NAME_TIPO_VEICULO)
  private String tipoVeiculo;

  public static final String SERIALIZED_NAME_SUB_SEGMENTO = "sub_segmento";
  @SerializedName(SERIALIZED_NAME_SUB_SEGMENTO)
  private String subSegmento;

  public static final String SERIALIZED_NAME_NUMERO_MOTOR = "numero_motor";
  @SerializedName(SERIALIZED_NAME_NUMERO_MOTOR)
  private String numeroMotor;

  public static final String SERIALIZED_NAME_NUMERO_CAIXA_CAMBIO = "numero_caixa_cambio";
  @SerializedName(SERIALIZED_NAME_NUMERO_CAIXA_CAMBIO)
  private String numeroCaixaCambio;

  public static final String SERIALIZED_NAME_POTENCIA = "potencia";
  @SerializedName(SERIALIZED_NAME_POTENCIA)
  private String potencia;

  public static final String SERIALIZED_NAME_CILINDRADAS = "cilindradas";
  @SerializedName(SERIALIZED_NAME_CILINDRADAS)
  private String cilindradas;


  public DadosTecnicos tipoVeiculo(String tipoVeiculo) {
    
    this.tipoVeiculo = tipoVeiculo;
    return this;
  }

   /**
   * Get tipoVeiculo
   * @return tipoVeiculo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTipoVeiculo() {
    return tipoVeiculo;
  }


  public void setTipoVeiculo(String tipoVeiculo) {
    this.tipoVeiculo = tipoVeiculo;
  }


  public DadosTecnicos subSegmento(String subSegmento) {
    
    this.subSegmento = subSegmento;
    return this;
  }

   /**
   * Get subSegmento
   * @return subSegmento
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubSegmento() {
    return subSegmento;
  }


  public void setSubSegmento(String subSegmento) {
    this.subSegmento = subSegmento;
  }


  public DadosTecnicos numeroMotor(String numeroMotor) {
    
    this.numeroMotor = numeroMotor;
    return this;
  }

   /**
   * Get numeroMotor
   * @return numeroMotor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNumeroMotor() {
    return numeroMotor;
  }


  public void setNumeroMotor(String numeroMotor) {
    this.numeroMotor = numeroMotor;
  }


  public DadosTecnicos numeroCaixaCambio(String numeroCaixaCambio) {
    
    this.numeroCaixaCambio = numeroCaixaCambio;
    return this;
  }

   /**
   * Get numeroCaixaCambio
   * @return numeroCaixaCambio
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNumeroCaixaCambio() {
    return numeroCaixaCambio;
  }


  public void setNumeroCaixaCambio(String numeroCaixaCambio) {
    this.numeroCaixaCambio = numeroCaixaCambio;
  }


  public DadosTecnicos potencia(String potencia) {
    
    this.potencia = potencia;
    return this;
  }

   /**
   * Get potencia
   * @return potencia
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPotencia() {
    return potencia;
  }


  public void setPotencia(String potencia) {
    this.potencia = potencia;
  }


  public DadosTecnicos cilindradas(String cilindradas) {
    
    this.cilindradas = cilindradas;
    return this;
  }

   /**
   * Get cilindradas
   * @return cilindradas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCilindradas() {
    return cilindradas;
  }


  public void setCilindradas(String cilindradas) {
    this.cilindradas = cilindradas;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DadosTecnicos dadosTecnicos = (DadosTecnicos) o;
    return Objects.equals(this.tipoVeiculo, dadosTecnicos.tipoVeiculo) &&
        Objects.equals(this.subSegmento, dadosTecnicos.subSegmento) &&
        Objects.equals(this.numeroMotor, dadosTecnicos.numeroMotor) &&
        Objects.equals(this.numeroCaixaCambio, dadosTecnicos.numeroCaixaCambio) &&
        Objects.equals(this.potencia, dadosTecnicos.potencia) &&
        Objects.equals(this.cilindradas, dadosTecnicos.cilindradas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipoVeiculo, subSegmento, numeroMotor, numeroCaixaCambio, potencia, cilindradas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DadosTecnicos {\n");
    sb.append("    tipoVeiculo: ").append(toIndentedString(tipoVeiculo)).append("\n");
    sb.append("    subSegmento: ").append(toIndentedString(subSegmento)).append("\n");
    sb.append("    numeroMotor: ").append(toIndentedString(numeroMotor)).append("\n");
    sb.append("    numeroCaixaCambio: ").append(toIndentedString(numeroCaixaCambio)).append("\n");
    sb.append("    potencia: ").append(toIndentedString(potencia)).append("\n");
    sb.append("    cilindradas: ").append(toIndentedString(cilindradas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

