/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VeiculoRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-30T10:01:03.531-03:00[America/Fortaleza]")
public class VeiculoRequest {
  public static final String SERIALIZED_NAME_PLACA = "placa";
  @SerializedName(SERIALIZED_NAME_PLACA)
  private String placa;


  public VeiculoRequest placa(String placa) {
    
    this.placa = placa;
    return this;
  }

   /**
   * Get placa
   * @return placa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPlaca() {
    return placa;
  }


  public void setPlaca(String placa) {
    this.placa = placa;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VeiculoRequest veiculoRequest = (VeiculoRequest) o;
    return Objects.equals(this.placa, veiculoRequest.placa);
  }

  @Override
  public int hashCode() {
    return Objects.hash(placa);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VeiculoRequest {\n");
    sb.append("    placa: ").append(toIndentedString(placa)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

