/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.fidias.consultar_placa.model.DadosCarga;
import br.com.fidias.consultar_placa.model.DadosTecnicos;
import br.com.fidias.consultar_placa.model.DadosVeiculo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VeiculoDadosInformacoesVeiculo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T10:48:15.845-03:00[America/Fortaleza]")
public class VeiculoDadosInformacoesVeiculo {
  public static final String SERIALIZED_NAME_DADOS_VEICULO = "dados_veiculo";
  @SerializedName(SERIALIZED_NAME_DADOS_VEICULO)
  private DadosVeiculo dadosVeiculo;

  public static final String SERIALIZED_NAME_DADOS_TECNICOS = "dados_tecnicos";
  @SerializedName(SERIALIZED_NAME_DADOS_TECNICOS)
  private DadosTecnicos dadosTecnicos;

  public static final String SERIALIZED_NAME_DADOS_CARGA = "dados_carga";
  @SerializedName(SERIALIZED_NAME_DADOS_CARGA)
  private DadosCarga dadosCarga;


  public VeiculoDadosInformacoesVeiculo dadosVeiculo(DadosVeiculo dadosVeiculo) {
    
    this.dadosVeiculo = dadosVeiculo;
    return this;
  }

   /**
   * Get dadosVeiculo
   * @return dadosVeiculo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DadosVeiculo getDadosVeiculo() {
    return dadosVeiculo;
  }



  public void setDadosVeiculo(DadosVeiculo dadosVeiculo) {
    this.dadosVeiculo = dadosVeiculo;
  }


  public VeiculoDadosInformacoesVeiculo dadosTecnicos(DadosTecnicos dadosTecnicos) {
    
    this.dadosTecnicos = dadosTecnicos;
    return this;
  }

   /**
   * Get dadosTecnicos
   * @return dadosTecnicos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DadosTecnicos getDadosTecnicos() {
    return dadosTecnicos;
  }



  public void setDadosTecnicos(DadosTecnicos dadosTecnicos) {
    this.dadosTecnicos = dadosTecnicos;
  }


  public VeiculoDadosInformacoesVeiculo dadosCarga(DadosCarga dadosCarga) {
    
    this.dadosCarga = dadosCarga;
    return this;
  }

   /**
   * Get dadosCarga
   * @return dadosCarga
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DadosCarga getDadosCarga() {
    return dadosCarga;
  }



  public void setDadosCarga(DadosCarga dadosCarga) {
    this.dadosCarga = dadosCarga;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VeiculoDadosInformacoesVeiculo veiculoDadosInformacoesVeiculo = (VeiculoDadosInformacoesVeiculo) o;
    return Objects.equals(this.dadosVeiculo, veiculoDadosInformacoesVeiculo.dadosVeiculo) &&
        Objects.equals(this.dadosTecnicos, veiculoDadosInformacoesVeiculo.dadosTecnicos) &&
        Objects.equals(this.dadosCarga, veiculoDadosInformacoesVeiculo.dadosCarga);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dadosVeiculo, dadosTecnicos, dadosCarga);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VeiculoDadosInformacoesVeiculo {\n");
    sb.append("    dadosVeiculo: ").append(toIndentedString(dadosVeiculo)).append("\n");
    sb.append("    dadosTecnicos: ").append(toIndentedString(dadosTecnicos)).append("\n");
    sb.append("    dadosCarga: ").append(toIndentedString(dadosCarga)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

