/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.fidias.consultar_placa.model.VeiculoDados;
import br.com.fidias.consultar_placa.model.VeiculoRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * Veiculo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T09:58:41.009-03:00[America/Fortaleza]")
public class Veiculo {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_MENSAGEM = "mensagem";
  @SerializedName(SERIALIZED_NAME_MENSAGEM)
  private String mensagem;

  public static final String SERIALIZED_NAME_DATA_SOLICITACAO = "data_solicitacao";
  @SerializedName(SERIALIZED_NAME_DATA_SOLICITACAO)
  private OffsetDateTime dataSolicitacao;

  public static final String SERIALIZED_NAME_DADOS = "dados";
  @SerializedName(SERIALIZED_NAME_DADOS)
  private VeiculoDados dados;

  public static final String SERIALIZED_NAME_REQUEST = "request";
  @SerializedName(SERIALIZED_NAME_REQUEST)
  private VeiculoRequest request;


  public Veiculo status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatus() {
    return status;
  }



  public void setStatus(String status) {
    this.status = status;
  }


  public Veiculo mensagem(String mensagem) {
    
    this.mensagem = mensagem;
    return this;
  }

   /**
   * Get mensagem
   * @return mensagem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMensagem() {
    return mensagem;
  }



  public void setMensagem(String mensagem) {
    this.mensagem = mensagem;
  }


  public Veiculo dataSolicitacao(OffsetDateTime dataSolicitacao) {
    
    this.dataSolicitacao = dataSolicitacao;
    return this;
  }

   /**
   * Get dataSolicitacao
   * @return dataSolicitacao
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getDataSolicitacao() {
    return dataSolicitacao;
  }



  public void setDataSolicitacao(OffsetDateTime dataSolicitacao) {
    this.dataSolicitacao = dataSolicitacao;
  }


  public Veiculo dados(VeiculoDados dados) {
    
    this.dados = dados;
    return this;
  }

   /**
   * Get dados
   * @return dados
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VeiculoDados getDados() {
    return dados;
  }



  public void setDados(VeiculoDados dados) {
    this.dados = dados;
  }


  public Veiculo request(VeiculoRequest request) {
    
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VeiculoRequest getRequest() {
    return request;
  }



  public void setRequest(VeiculoRequest request) {
    this.request = request;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Veiculo veiculo = (Veiculo) o;
    return Objects.equals(this.status, veiculo.status) &&
        Objects.equals(this.mensagem, veiculo.mensagem) &&
        Objects.equals(this.dataSolicitacao, veiculo.dataSolicitacao) &&
        Objects.equals(this.dados, veiculo.dados) &&
        Objects.equals(this.request, veiculo.request);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, mensagem, dataSolicitacao, dados, request);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Veiculo {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    mensagem: ").append(toIndentedString(mensagem)).append("\n");
    sb.append("    dataSolicitacao: ").append(toIndentedString(dataSolicitacao)).append("\n");
    sb.append("    dados: ").append(toIndentedString(dados)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

