/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.fidias.consultar_placa.model.VeiculoDadosInformacoesVeiculo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VeiculoDados
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-29T10:44:02.849-03:00[America/Fortaleza]")
public class VeiculoDados {
  public static final String SERIALIZED_NAME_INFORMACOES_VEICULO = "informacoes_veiculo";
  @SerializedName(SERIALIZED_NAME_INFORMACOES_VEICULO)
  private VeiculoDadosInformacoesVeiculo informacoesVeiculo;


  public VeiculoDados informacoesVeiculo(VeiculoDadosInformacoesVeiculo informacoesVeiculo) {
    
    this.informacoesVeiculo = informacoesVeiculo;
    return this;
  }

   /**
   * Get informacoesVeiculo
   * @return informacoesVeiculo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VeiculoDadosInformacoesVeiculo getInformacoesVeiculo() {
    return informacoesVeiculo;
  }



  public void setInformacoesVeiculo(VeiculoDadosInformacoesVeiculo informacoesVeiculo) {
    this.informacoesVeiculo = informacoesVeiculo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VeiculoDados veiculoDados = (VeiculoDados) o;
    return Objects.equals(this.informacoesVeiculo, veiculoDados.informacoesVeiculo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(informacoesVeiculo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VeiculoDados {\n");
    sb.append("    informacoesVeiculo: ").append(toIndentedString(informacoesVeiculo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

