/*
 * API de Histórico Veicular
 * Consulte o histórico completo de veículos usando apenas a placa com a API do Consultar Placa.
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: contato@consultarplaca.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.consultar_placa.api;

import br.com.fidias.consultar_placa.ApiException;
import br.com.fidias.consultar_placa.model.Error;
import br.com.fidias.consultar_placa.model.Veiculo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void consultarPlacaGetTest() throws ApiException {
        String placa = null;
        Veiculo response = api.consultarPlacaGet(placa);

        // TODO: test validations
    }
    
}
